[supervisord]
nodaemon=true

[program:mysql]
command=/usr/sbin/mysqld --disable-log-bin
autostart=true
autorestart=true

[program:redis]
command=/usr/bin/redis-server
autostart=true
autorestart=true

[program:apache]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true

[program:cron]
command=/usr/sbin/cron -f
autostart=true
autorestart=true
